### PR TITLE
Mr kings

### PR DESCRIPTION
**Pull request by Mr-kings042**
created and updated the account stimulator with transaction, user login and account authentication etc.

### CODE REVIEW

**Comment by joshuaunity** [comment]
Hi @Mr-kings042 i cant find your insomnia or postman collection file or link here

**Comment by joshuaunity** [comment]
Hi, @Mr-kings042 I am testing right now and I saw something that will need to be rectified. In your project you have an Account model and a User model, this is not particularly bad but the account model is what is serving as the user model for this case so having a separate User model will be an unnecessary duplicate.

So, go ahead and remove the User part and leave the account part.

Here are some other things I noticed.

1. Whn creating an account the system should be the one to generate the account number and not the individual.

**Comment by Mr-kings042** [comment]
I have added the function that generates 10 random account number in the create account api

**Comment by joshuaunity** [comment]
> I have added the function that generates 10 random account number in the create account API


Great, currently reviewing

**Comment by joshuaunity** [comment]
Hi @Mr-kings042 I tried creating an account and got the below validation response.


{
    "error": "Name, Email and Password required"
}


Check your code, cause im not suppose to me require all these to create an account as I am a new user

**Comment by joshuaunity** [comment]
Hi @Mr-kings042,

Here are the findings from my review:

The following APIs are not functioning and return the error message "cannot 'method' 'resource'", indicating that the API endpoints may not exist:

1. Delete account
2. update account
3. Get account transactions
4. deposit api
5. Withdrawal API

Example error: "Cannot POST /accounts/withdraw/"

Please review and address these issues. Also, keep up the good work 💪🏾

**Comment by joshuaunity** [comment]
Good work, everything works fine now. But I cant merge this as it seems there is some conflict between this branch and the main branch.

Look into the conflict so the PR will be unblocked from being merged

**Pull request merged**
